import streamlit as st
from utils import page_style, footer

st.set_page_config(page_title="Theory | MM-1887", page_icon="📐", layout="wide")
page_style()
st.title("06 · Theory")
st.subheader("Physics behind the reconstruction")
st.markdown("### 1. Parallel arm")
st.latex(r"t_{\parallel}=\frac{L}{c-v}+\frac{L}{c+v}=\frac{2Lc}{c^2-v^2}")
st.markdown("### 2. Perpendicular arm")
st.latex(r"t_{\perp}=\frac{2L}{\sqrt{c^2-v^2}}")
st.markdown("### 3. Differential time")
st.latex(r"\Delta t=t_{\parallel}-t_{\perp}")
st.markdown("### 4. Second-order fringe prediction")
st.latex(r"N_{\max}=\frac{2L}{\lambda}\left(\frac{v}{c}\right)^2")
st.markdown("For the historical scale L ≈ 11 m, v ≈ 30 km/s and visible light λ ≈ 550 nm, this gives a predicted shift of approximately 0.4 fringe.")
st.markdown("### 5. Why rotation matters")
st.markdown("The two perpendicular arms respond differently to the hypothetical ether wind. Rotating the apparatus swaps their orientation relative to that wind, producing a second-order angular dependence.")
st.latex(r"N(\theta)\propto\cos(2\theta)")
st.markdown("### 6. Historical caution")
st.markdown("Michelson and Morley tested the ether hypothesis; Einstein's 1905 Special Relativity was a later theoretical framework with the postulate that the speed of light in vacuum is invariant for inertial observers. Lorentz, Fitzgerald, Poincaré and others also contributed to the development of the ideas surrounding the null result.")
st.markdown("### Reference")
st.markdown("A. A. Michelson & E. W. Morley, *On the Relative Motion of the Earth and the Luminiferous Ether*, American Journal of Science (1887).")
footer()
